In [27]:
import numpy as np

A = np.array([[3,6,7],[5,-3,0],[4,7,10]])

print('A is: ', A)

B = np.transpose(A)
print('B is: ', B)

inverse = np.linalg.inv(A)

print('Inv is: ', inverse)

print('Eig Vals are: ',np.linalg.eigvals(A))
print('##########')

B = A + 4
print('New B is: ', B)

np.sqrt(B)

np.remainder(A,B)

np.mean(A,axis = 0)
np.std(A)

C = np.array([[0.0,0],[0,0]])
print('C is: ', C)
np.prod(C)

A is:  [[ 3  6  7]
 [ 5 -3  0]
 [ 4  7 10]]
B is:  [[ 3  5  4]
 [ 6 -3  7]
 [ 7  0 10]]
Inv is:  [[ 0.49180328  0.18032787 -0.3442623 ]
 [ 0.81967213 -0.03278689 -0.57377049]
 [-0.7704918  -0.04918033  0.63934426]]
Eig Vals are:  [14.3677305   0.81861584 -5.18634634]
##########
New B is:  [[ 7 10 11]
 [ 9  1  4]
 [ 8 11 14]]
C is:  [[0. 0.]
 [0. 0.]]


0.0

In [28]:
np.all(C)
np.any(C)

False

In [34]:
#### if loop 
a = 18
b = 3

#a <= b

if a == b:
    c = a
elif a > b + 4:  ### 18>7
    
    if a < b + 10:
        c = 2*a
    else:
        c = 3*a  #### 3*18 = 54
else:
    c = b

print('C is: ', c)
    

C is:  54


In [38]:
A = np.arange(2,14,3)
print(A)

count = 0
for i in A:
    if i >= 5:
        count += 1

print('Count is: ', count)

[ 2  5  8 11]
Count is:  3


In [50]:
### in-class exercise

A_score = 90
B_score = 80
C_score = 70
D_score = 60
### F_score < 60

score = int(input('Enter your test score: '))
 
# Determine the grade.
if score >= A_score:
    print('Your grade is A.')
elif score >= B_score:
    print('Your grade is B.')
elif score >= C_score:
    print('Your grade is C.')
elif score >= D_score:
    print('Your grade is D.')
else:
    print('Your grade is F.')


Enter your test score: 89
Your grade is B.


In [56]:
ord('a')

False


97

In [57]:
ord('A')

65

In [62]:
print('aAa' > 'aAaAA')

False


In [67]:
name1 = input('Enter name 1: ')
name2 = input('Enter name 2: ')
print('The name in alphabetical order is: \n')

if name1 <= name2:
    print(name1,'\n',name2)

#print(name2)
else:
    print(name2,name1)
    #print(name1)

Enter name 1: alph1
Enter name 2: alph2
The name in alphabetical order is: 

alph1 
 alph2


In [69]:
### in-class exercise: sort the fruit in alphabetical order
Fruit = ['Apple','Orange','Pear','Banana','Pineapple','Grape','Melon']

In [70]:
for i in range(0,len(Fruit)-1):
    for j in range(i+1,len(Fruit)):
        if Fruit[i]>Fruit[j]:
            Fruit[i], Fruit[j] = Fruit[j], Fruit[i]
        
#####
print('The fruit in aphabetical order is:',Fruit)

The fruit in aphabetical order is: ['Apple', 'Banana', 'Grape', 'Melon', 'Orange', 'Pear', 'Pineapple']


In [91]:

A = np.arange(2,14,3)

count2 = 0
for i in A:
    count2 += 1 if i>=5 else count2   ### compact shorthand command

print(count2)

A = np.arange(2,14,3)



3


In [87]:
A = np.arange(2,14,3)
B = np.arange(5,15,2)

print('A is: ', A)
print('B is: ', B)



common = 0
for i in A:
    if i in B:
        common += 1
print(common)

A is:  [ 2  5  8 11]
B is:  [ 5  7  9 11 13]
2
