In [10]:
##### list 
X = [1,2,3]
Y = [4,5,6]

ans = zip(X,Y)

S = 0
#for i in ans:
 #   print(i)
  #  S = S + i[0] + i[1]
#print('Total summation is: ', S)



S2 = 0
for (i,j) in ans:
    #print(j)
    S2 = S2 + i + j
print('New sum: ',S2)


New sum:  21


In [67]:
A = [[1,4,5,12],[-5,8,9,0],[-6,7,11,19]]

#A[0][0]

B = A
### calculate the summation of all elements in both A and B using zip funciton.
i = [1, 4, 5, 12]
j = [1, 4, 5, 12]

Summation = 0 
for (i,j) in zip(A,B):  
    for (val1,val2) in zip(i,j):   
        Summation = Summation + val1 + val2
#print('Total sum is: ', Summation)


sum_List = B
##print(sum_List)
i = 0  #### looping over each row

for (ele1, ele2) in zip(A,B):
    j = 0
    for (val1,val2) in zip(ele1,ele2):
        sum_List[i][j] = val1 + val2
        j+=1
    i+=1
print(sum_List)

A = [[1,4,5,12],[-5,8,9,0],[-6,7,11,19]]

Second = []
for i in range(3):
    Second.append(A[i][1])
Second


Third = []
for row in A:    
    print(row)
    print(row[2])
    Third.append(row[2])
Third

[[2, 8, 10, 24], [-10, 16, 18, 0], [-12, 14, 22, 38]]
[1, 4, 5, 12]
5
[-5, 8, 9, 0]
9
[-6, 7, 11, 19]
11


[5, 9, 11]

In [65]:
import numpy as np

x = np.array([-1, 0, 2, 3.2])
x
y = x

z = x.copy()

print('old z is: ', z)
print('old y is: ', y)
x[2] = 10

print('new x is:', x)

print('your y is: ', y)
print('your z is: ', z)

y == x

xarray = np.array([1,2,3], dtype = float)
xarray

A = np.array([[1,4,5,1],[3,2,3,7],[7,6,3,0]])
print(A)
type(A)
(row,col) = A.shape
row

A[0][0]
A[:,1]

A[1,:]
A[1]

old z is:  [-1.   0.   2.   3.2]
old y is:  [-1.   0.   2.   3.2]
new x is: [-1.   0.  10.   3.2]
your y is:  [-1.   0.  10.   3.2]
your z is:  [-1.   0.   2.   3.2]
[[1 4 5 1]
 [3 2 3 7]
 [7 6 3 0]]


array([3, 2, 3, 7])