In [5]:
import numpy as np

A = np.array([[1,4,5,12],[-5,8,9,0],[-6,7,11,19]],dtype = int)

A



array([[ 1,  4,  5, 12],
       [-5,  8,  9,  0],
       [-6,  7, 11, 19]])

In [17]:
np.min(A,axis = 1)
np.max(A,axis = 0)
A[0][0]


### use for loop to calculate the summation of all elements in A
summation = 0
for i in A:
    #print(i)
    for j in i:
        summation = summation + j

print('summation: ',summation)
        
    


summation:  65


In [22]:
B1 = np.array([1,3])
B2 = np.array([2,4])
B3 = np.array([0,10])

B = np.array([B1,B2,B3])
B

array([[ 1,  3],
       [ 2,  4],
       [ 0, 10]])

In [38]:
(row,col) = B.shape
print('row is: ', row, 'col is:', col)

np.zeros((row,col),dtype = int)

a = np.ones((row,col+1),dtype = int)
a


row is:  3 col is: 2


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
a[0,1] = 3
a[0,:] = [2, 4, 5]

a

array([[2, 4, 5],
       [1, 1, 1],
       [1, 1, 1]])

In [61]:
#### syntax for arange is: np.arange(start,stop,step)

A = np.arange(1,4,2)
A = np.arange(3.5)
A = np.arange(0,5,2)
#A = np.arange(4)
A


### syntax for linspace: np.linspace(start,stop,number)
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [66]:
A = np.array([1,2,3])
B = np.array([10,20,30])
print('A is: ', A)
print('B is: ', B)

print(A*B)

A is:  [1 2 3]
B is:  [10 20 30]
[10 40 90]


In [75]:
p_ini = np.array([22,89,56])
p_f = np.array([23,87,53])
r = (p_ini - p_f)/p_ini

a = np.array([1,2])
3*a

b = np.array([3,4])

alpha = -0.5
beta = 1.5

c = alpha*a + beta*b

c[0]
#c[1]
#print('my c is:', c)
1*-0.5+1.5*3

a*b
np.inner(a,b)  ### a times transpose of b
a@b


array([3, 4])

In [93]:
### make a matrix with reshape function 
B = np.arange(12)
print('My B is: ', B)

C = B.reshape(3,4)
print('My C is: ', C)

D = np.linspace(1,12,12).reshape(3,4)

print('My D is: ', D)

My B is:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
My C is:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
My D is:  [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [105]:
A = np.array([[3, 6, 7],[5, -3, 0]])
B = A.reshape(3,2)

print('A is: ',A)
print('B is: ',B)

C = A.dot(B)
C = np.dot(A,B)
print('My C is:', C )

E = np.matmul(A,B)   ### recommended
print('My E is: ', E)


np.identity(4,dtype = int)

np.diag(np.arange(0,20,5))

np.random.rand(3,4)

A is:  [[ 3  6  7]
 [ 5 -3  0]]
B is:  [[ 3  6]
 [ 7  5]
 [-3  0]]
My C is: [[30 48]
 [-6 15]]
My E is:  [[30 48]
 [-6 15]]


array([[0.21628167, 0.30432391, 0.48171746, 0.09983236],
       [0.39864284, 0.79783394, 0.59609717, 0.78960632],
       [0.47372233, 0.16643394, 0.56923876, 0.45833641]])